const csvData = {
    "Ahmad Yani": [
        ["Nama", "No HP/WA", "Alamat", "Rate Makanan", "Rate Pelayanan", "Rate Kenyamanan", "Rate Kebersihan", "Kritik dan Saran"],
        ["Dedes", "81339318318", "-", "Enak Sekali", "Baik", "Nyaman", "Bersih", "-"],
        ["Bayu", "81321148301", "Gatsu", "Enak Sekali", "Baik Sekali", "Tidak Nyaman", "Bersih Sekali", "BAYAR PARKIR!!! Juru parkir ga niat kerja, kadang ada kadang ga ada. Beli ayam udah kena tax, lagi harus bayar parkir???"],
        ["JORDAN", "-", "-", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Sudah oke, Sabun di wastafel habis sering di isi."],
        ["Anom", "81999533336", "-", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Ayam", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Putu Eka", "8174745644", "Ubung Kaja", "Enak", "Baik Sekali", "Nyaman", "Bersih Sekali", "-"],
        ["Pandi Pandu", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "Mantap"],
        ["Eca", "81949718821", "Perum. Yani Permai", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "Tidak ada karena sudah best!!!"],
        ["I.G.N. Pt. Ardana", "85100849210", "Sempidi", "Enak", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["Ika", "87780391788", "Cokroaminoto", "Enak", "Baik", "Nyaman", "Bersih", "Tolong sesekali cek ketersediaan tisu untuk cuci tangan dan kurang mengarahkan customer ketersediaan lalapan gratis, selain itu semua sudah cukup bagus ♥️"],
        ["Bima", "81210579795", "Surapati", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["I Nyoman Brani", "81731953327", "Jln. Melasti Suna no. 4. Kedonganan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Tidak ada, semua ramah."],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik", "Nyaman", "Biasa", "-"],
        ["De Agus", "-", "Ayani", "Enak", "Baik", "Nyaman Sekali", "Bersih", "Kalau Bisa Sediakan Ashtray."],
        ["(anonim)", "-", "-", "Enak", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["(anonim)", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Victoria", "82131287375", "Denpasar", "Enak", "Baik", "Nyaman", "Bersih", "Beda cabang beda rasa."],
        ["ANING", "82338640136", "Ametung X no. 7B", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "SAMBALNYA UDAH MANTEPP...!!! (porsinya banyakin donk sambalnya...)"],
        ["Ayu Mesiani Putri", "-", "Denpasar utara", "NULL", "NULL", "NULL", "NULL", "-"],
        ["Andaru", "Semangat kak. Sukses Enakko ^^", "-", "Enak", "Baik", "Nyaman Sekali", "Biasa", "opening sambutan kasirnya terlalu panjang. Selebihnya bagus.... Oh iya, kursinya kependekan :) ♥️ ☆"],
        ["Ririn", "81805602479", "Tunjung Tutur", "Enak", "Baik", "Nyaman", "Bersih", "Kalau bisa ada sambal bawang yang tidak pedas, supaya bisa menikmati kebuli dengan sambal yang tidak panas di mulut. terima kasih :)"],
        ["Sastra", "85204113349", "Suradipa", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Ayam & nasi enak tapi maaf kebetulan lalapan yg saya ambil kurang bersih. Selebihnya mantap semua :("],
        ["Amanda Salsha", "81237686842", "JL. Gunung Agung Gg. IIA. No. 9", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Lebih di perbanyak cabangnya :)"],
        ["Nita", "81523806685", "Lembu Sora", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "Sudah mantap!"],
        ["(anonim)", "-", "-", "Enak", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["Jon", "-", "Abian Semal", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["Dicky", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Arya Wiguna", "821037244986", "Gang Karunia, no. 30", "Enak Sekali", "Baik", "Biasa", "Bersih", "-"],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["I Made Angkasa C", "81816258831", "Perum Ayani BR Padang Kacul", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "good food, good service. good taste, all the best, Top"],
        ["Diah", "81805586232", "Tabanan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["No Name", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "Enak, Sukses Selalu !!"],
        ["Jamal", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Kadek Ediasih", "87710771577", "Jln. Suradipa II. Gg. Taman Ayun", "Enak", "Baik", "Biasa", "Bersih", "Rasa asin terlalu dominan dari kuahnya"],
        ["Harson", "87894960707", "Ken Umang, gang H, Ubung", "Enak", "Baik Sekali", "Nyaman", "Bersih Sekali", "The Best bakal kesini lagi"],
        ["Nia", "81803149906", "Jl. Lembu Sora V", "Enak", "Baik", "Nyaman", "Bersih", "Tambah sayur untuk menu take away. Tidak ada tissue di Meja Makan."],
        ["Putri", "895339537729", "Ayani Utara", "Enak Sekali", "Baik", "Biasa", "Bersih", "-"],
        ["Bambang", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Tidak ada. This is The Best Food in the world. Terbaik Se-Denpasar ♥"],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Gek Sri", "85739360222", "Tabanan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Putra", "08778081037634024", "Peguyangan", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Kurang toilet"],
        ["(anonim)", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "Nasi Kebulinya jangan terlalu menggumpal"],
        ["I Putu Adi Mahendra", "81338206775", "Sibang Kaja", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Ni Putu Devi Meisa Putri", "81929246866", "Jl Raya Angantaka no D2", "Enak", "Baik", "Nyaman", "Bersih", "Tidak ada semuanya sudah keren sekali, semangat terus ya :)"],
        ["Ibas", "81353440422", "Br. Penenjoan, Darmasaba", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Putu Lina Prawesti", "87853248425", "Jln Blambangan IV no 18", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Silvi", "87700959299", "Jl. Gn. Agung Barat", "Enak", "Baik Sekali", "Nyaman", "Bersih Sekali", "By. Ayam dengan tekstur yang ringan tidak berlemak dengan cita rasa bumbu yang berempah sekali. Dipadu dengan nasi yang berempah mild cocok untuk makan sehari-hari dan oleh-oleh khas Bali."],
        ["Tude", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["(anonim)", "-", "-", "Enak Sekali", "Biasa", "Nyaman", "Bersih", "-"],
        ["(anonim)", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "Saran dari kami hanya agar di harap ke tissu setelah kami makan dan cuci tangan perlu tissu, trim's"],
        ["Ayu Melina", "85730702671", "Jl Lembu sora 1 Gd 3", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "Semoga rasanya konsisten ya"],
        ["Gung Alit", "87850507023", "Peguyangan", "Enak", "Baik", "Nyaman", "Bersih", "Baik. Good."],
        ["De Ju", "-", "Ubud", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Anggun", "-", "A Yani Gang Cempaka", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["MELLODY", "83129636708", "JL. MADEBINA", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih", "-"],
        ["Tantra", "-", "Jl Petanu I", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Pelayanan perlu dimaksimalkan. Pertahankan rasa ayam tetap konsisten."],
        ["Putu", "-", "Sukawati", "Biasa", "Baik", "Nyaman", "Bersih", "-"],
        ["Frendy", "812456321781", "Pemogan 86", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Bumbu rempahnya kurang mantap lagi.."],
        ["Debi", "-", "Jl. Subak dalem", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Enak, Bintang 5 ☆☆☆☆☆"],
        ["Ngurah", "-", "UBUNG - DPS", "Enak Sekali", "Baik", "Nyaman", "Bersih", "-"],
        ["Mila", "-", "-", "Enak", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["(anonim)", "-", "-", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Saran mungkin disetiap meja disediakan kotak tissue"],
        ["(anonim)", "-", "-", "Biasa", "Baik", "Nyaman", "Bersih", "-"],
        ["(anonim)", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "overall enak, hanya ayamnya sedikit asin."],
        ["Adi", "-", "DPS", "Enak", "Biasa", "Biasa", "Biasa", "Finishing meja & kursi lebih rapi agar anak kecil nyaman"],
        ["Insta", "881037224271", "-", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Saran: Enakko Ahmad yani Sudah Sangat memuaskan, #Saya sendiri melihat brand ini sebagai makanan yg sehat, lebih bagus lg apabila ada paket yg sehat, Ayam + nasi + air tanpa ada tehnya jadi berasa paket sehat."],
        ["Fg Rutha Shanti", "08238054422 / 081238054422", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Semoga lebih baik dan rame lagi penjualannya :)"],
        ["(anonim)", "-", "-", "NULL", "NULL", "Biasa", "Bersih", "BAIK, PERLU DI TINGKATKAN."],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Ayutya", "81358763171", "Lembusura", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "✓"],
        ["Putra", "82146347473", "Denpasar", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Doni", "87850227859", "-", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih", "-"],
        ["Erwan Tribayu Surya", "8179755025", "Ling. Padang Udayana III/I", "Enak", "Baik", "Nyaman", "Bersih", "Terima kasih pelayanannya. Standart pelayanan fasilitas dan karyawan cukup baik."],
        ["Ich", "-", "-", "Enak Sekali", "Baik", "Biasa", "Bersih", "Sudah baik, bisa panggang ayamnya atau serve lebih hangat !! Semangat kerja kak :)"],
        ["(anonim)", "-", "-", "Enak", "Baik", "Biasa", "Biasa", "-"],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Koko Sukarma", "85829182210", "Taman Graha", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Kadek Dedi", "-", "Mambal Semane", "Enak", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["Kaivan", "82227577768", "Ayani Utara No 33", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Putri", "-", "Jln. Patih Nambi", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Sausnya mungkin bisa agak dibanyakin"],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Yos", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "Porsi ayam tiap piring tidak sama besar, Tiap meja perlu ditambahkan Tisu,"],
        ["Wardani", "85963064697", "Tabanan", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Hera Julian", "87860399745", "Badung", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Bayu", "81239984821", "Ubung", "Enak", "Baik", "Nyaman", "Bersih", "Porsi sambal pada paket single terlalu sedikit."],
        ["Nyongbex", "88297521306", "gang tok saya", "Enak Sekali", "Baik", "Nyaman", "Bersih", "BAIK"],
        ["(anonim)", "-", "-", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Donny", "81339800432", "Patih Nambi", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih", "-"],
        ["Excel", "8214453321", "Jl. RAYA RENON", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Gusti Astrawan", "81246707421", "Tabanan", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Berikan tisu saat bawa makanan u/ cust. Dine in, layar TV u/ menu terlalu cepat. Tukang parkir tidak nyebrangin cust yg datang. Example: Pertabak Adam Ayani rame."],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik", "Nyaman", "Biasa", "+ tisu"],
        ["Lim Tong Ng", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "LALAPAN KADANG2 TDK LENGKAP"],
        ["Rio", "-", "-", "Enak", "Biasa", "Biasa", "Bersih", "-"],
        ["Agus", "-", "Perum Andika Graha II", "Enak", "Baik", "Nyaman", "Bersih", "Sukses dan berkembang pesat usaha ayam guling enakko... GOD Bless You all amen Makasih :)"],
        ["Wiga", "-", "Jl. Satya", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Wahyu Aji", "82134397733", "-", "Enak Sekali", "Baik", "Nyaman", "Bersih", "- Harga gofood/online selisihnya berjauh sekali (mahal). - Paket Ayam 1/2 + Nasi 1 (Belum ada). - Tissue wastafel habis !!"],
        ["Joseph", "81225788245", "Tabanan", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Porsi nasi agak banyakin lagi"],
        ["Henry", "81916366668", "jl nangka utara no 8", "Enak", "Baik", "Nyaman", "Bersih", "kl bisa ada nasi uduk"],
        ["Pika", "-", "Ayani Utara", "Enak", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["Anonim", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "NULL", "Porsi sambal/porsi kurang banyak/penuh"],
        ["Dila", "-", "-", "Enak Sekali", "Baik", "Biasa", "Bersih", "-"],
        ["(tidak terbaca)", "(tidak terbaca)", "(tidak terbaca)", "Enak", "Biasa", "NULL", "Biasa", "-"],
        ["Wisam", "87875003799", "jl. Cokroaminoto, gg swan C 10", "Biasa", "Baik Sekali", "Nyaman", "Bersih", "Ayam nya masih kurang berasa bumbu nya dibanding dengan cabang lain contoh cabang pemogan"],
        ["Ayu", "-", "Denpasar", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Wulan & Turah", "-", "Tabanan", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["Diana Asti", "81916339226", "Jl. Noja", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "tidak ada, pertahankan semuanya. Terima kasih :)"],
        ["Madram", "-", "Sedang", "Enak", "Baik", "Biasa", "Bersih Sekali", "-"],
        ["Dinda", "89696727317", "JL. Srikarya No: 3", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Semoga karyawannya lebih disejahterakan lagi. Semangat !!! ♥"],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Aditya", "81286033699", "Abiansemal", "Enak", "Baik", "Nyaman", "Bersih", "Kalau bisa ga usah ada tukang parkir..!"],
        ["Putu Bagas Wijaya Putra", "85378516716", "Jl. Tunjung tutur", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Gung Sudiksa", "-", "Denpasar", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["(anonim)", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Yogi", "877861818967", "-", "Enak", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["Krisna", "89529385511", "JL. TUNGGUL AMETUNG", "Enak", "Baik", "Biasa", "Bersih", "-"],
        ["Aprilia / Steven", "85739821362", "Sidakarya", "Enak", "Baik", "Nyaman", "Bersih Sekali", "kalo bisa ada asbak ya kak, buat yang ngerokok, sama birnya juga."],
        ["Ciri", "-", "Tabanan", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Emma", "82123631991", "Jalan Patih Nambi", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Manda", "-", "Lukluk", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Robin", "-", "Ahmad Yani", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Suka tempatnya crew nya ramah-ramah."],
        ["Kuthi Asih", "87851812911", "Mengwi", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Teja", "81265366195", "lembu sora", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Nanda Bella", "81353350572", "Jl. Lembusora I Gg LT B No. 1", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Thia", "87761661346", "-", "NULL", "Baik", "Biasa", "Bersih", "-"],
        ["(anonim)", "-", "-", "Enak", "Baik", "Nyaman", "Bersih", "Enak banget jangan diutik-utik lagi"],
        ["Dwipa", "81288882606", "Perum Wisesa Mutiara", "Enak", "Baik", "Nyaman", "Bersih Sekali", "-"],
        ["Jro", "8191163953", "Ahmad Yani", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Dipertahankan & Ditingkatkan!"],
        ["Ita Kanaya", "81338646490", "Ayani", "Enak", "Baik Sekali", "Biasa", "Bersih", "Mungkin bisa ditutup ruangannya terus ditambah (AC) (Kalau siang panas)"],
        ["Erna", "-", "Badung", "Enak", "Baik", "Nyaman", "Biasa", "-"],
        ["Gede", "81529879030", "Putih Nambi", "Enak", "Baik", "Biasa", "Bersih", "OVERALL OKE. TOLONG KONDISIKAN ANJING LIAR YANG GALAK MENGGANGGU ORANG MAKAN :("],
        ["Anggita", "81301576385", "Sempidi, Betuus", "Enak", "Baik Sekali", "Nyaman", "Bersih Sekali", "-"],
        ["Dwi", "81517377015", "Abiansemal", "Enak Sekali", "Baik", "Nyaman", "Bersih", "-"],
        ["Jinia Rahmi", "81236337707", "Jl Zamrud no 17", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "mantapp."],
        ["Yulinda", "-", "Tabanan", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Cok", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Anyaa", "-", "Jl GN Catur IV", "Enak Sekali", "Baik", "Nyaman", "Bersih", "-"],
        ["Bagus Sadewa", "81338057046", "Jl Patih Nambi kavling telkom no. 11", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih Sekali", "-"],
        ["drh. Tedha", "81331865161", "Ahmad Yani Utara", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih", "-"],
        ["Ayu P.", "-", "-", "Enak", "Baik Sekali", "Nyaman", "Bersih", "pelayanan sudah OK, Makanan enak. mungkin porsi sambal bisa lebih banyak."],
        ["Trisna", "82147317448", "Jl. Tanah Putih Gg busana I, Sibang", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Diberi musik agar tambah rame u/ mengundang cust :)"],
        ["Nirmala", "81337130205", "Jl. Tunggul Ametung", "Enak Sekali", "Baik", "NULL", "Biasa", "Tolong tambah wastafel di dekat baliho, dekat garase kuning, trims"],
        ["Gede SP", "81353300091", "Sesetan Scorpio", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Kurang Tissue kak :)"],
        ["Vina", "87163222708", "-", "Enak", "Baik", "Nyaman", "Bersih", "Ladanya banyak bgt jadi pedas :) yang lainnya okay ♥️ Tissu wastafelnya jgn lupa direfil ya mas :)"],
        ["Esa Wiarpha", "87858967889", "Mengwi Badung", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Tempat nyaman & Rapi, Pelayanan Ramah."],
        ["Mikela Grad.", "8181625851", "A. Yani", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "Pelayanan Sangat Bagus Sekali \"Top\" di pertahankan \"good\""],
        ["Vira", "82146398900", "JL. CARGO TAMAN 3", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "-"],
        ["Rabih", "-", "Ubud", "Enak", "Baik", "Nyaman", "Bersih", "Sudah enak."],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Puput & Ajin", "-", "Badung", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "☆☆☆☆ Thank you :)"],
        ["Anjali", "-", "-", "Enak Sekali", "Baik", "Biasa", "Bersih", "By far semuanya sudah baik, tapi mungkin mejanya kurang di perbanyak saja !! :)"],
        ["Alex Budianto", "82170258571", "Taman Lembusora V1/28", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Rasa ayam enak, untuk Kentang goreng masih biasa, sambal enak, porsi cukup baik, ada lalapan nilai tambah"],
        ["Yogi", "81917089667", "JL. ASTASURA I", "Enak", "Baik", "Nyaman", "Bersih", "Good Job ♥"],
        ["Andy", "81916578788", "Badung", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Pertahankan"],
        ["Fajar", "-", "blahkiluh", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Saya suka rasa masakanya dan harganya terjangkau menurut saya worth it"],
        ["Vivi", "87840901010", "JL. A.yani utara", "Enak Sekali", "Baik", "Biasa", "Bersih", "mungkin utk ruangan di bagi 2 non AC dan AC"],
        ["Julius", "87760193007", "JL Ayani utara no 155", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["Maitri Kirania", "0811-3977-272", "Jln. Kori Agung No.1 Sading, Mengwi, Badung", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Eka", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Ni Made Ayu Andila", "85847139298", "Jl. Teuku umar Gg. Sesapi", "Enak", "Baik", "Biasa", "Bersih", "-"],
        ["Lalu Ardhim", "85238157326", "Tabanan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Saran -> buka lebih banyak store di seluruh bali ♥"],
        ["Arief", "81273436629", "Patih Nambi", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Buat taburan kentang gorengnya Bikin pakai garamnya mash"],
        ["Sunyu", "-", "Gatsu Timur", "Enak", "Baik", "Nyaman", "Bersih", "Porsi nasi ditambah sedikit lagi, terlalu sedikit.. :)"],
        ["Lukpita", "89618450899", "Ubung", "Enak Sekali", "Baik", "Nyaman", "Bersih", "-"],
        ["Nanda Satria A", "85117110817", "Nangka Utara Gg Musa Indah No 7", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "UDAH PAS SEMUA"],
        ["Khrisna", "-", "Ayani gg sriti", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "tisu di meja, kalau bisa hrs cpt clean up kalau customer udah pergi. thankyou. (Pas rame ya :))"],
        ["Zia", "-", "-", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "-"],
        ["Pipit putria", "85156168735", "Gg. Malrboro", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih Sekali", "Mungkin ditambah lagi menu minumnya seperti es jeruk"],
        ["Dyah pradnya", "85935325835", "sedang, Badung", "Enak", "Baik", "Nyaman", "Bersih", "Porsi sambal kurang banyak"],
        ["(anonim)", "-", "-", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "-"],
        ["Nia", "8983149906", "Jl. Lembu Sora", "Enak", "Baik", "Nyaman", "Bersih", "Beri sayur untuk menu yang dibawa pulang - Buat menu berkah dengan Air mineral juga"],
    ],
    "Dalung": [
        ["Nama", "No HP/WA", "Alamat", "Rate Makanan", "Rate Pelayanan", "Rate Kenyamanan", "Rate Kebersihan", "Kritik dan Saran"],
        ["Lina Febriani", "0881038048112", "Jl. Pdg. Luwih no. 72", "Enak", "Baik", "Nyaman", "Bersih", "Mantap. Sambal koreknya wajib banget."],
        ["Komang Artayasa", "089697170527", "Perumahan Anggri Elok", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Ayamnya mungkin kurang krispy dan hangat. Sambalnya enak. Porsinya banyak ❤️."],
        ["Devi Zahran", "0895331293689", "Perumahan Anggri Elok", "Enak", "Baik", "Nyaman Sekali", "Bersih Sekali", "Ayamnya mungkin bisa lebih hangat. Sambalnya enak banget. Porsinya banyak ❤️."],
        ["Rosmawati", "082165211453", "Buduk", "Enak", "Baik", "Nyaman", "Bersih", "Ayamnya kurang panas, coba kalo panas makanannya tambah semangat HEHE. Sediakan tong sampah di wastafel belakang. Sediakan tissu di Meja Makan. Sukses Selalu."],
        ["Naren", "-", "Dalung", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["Pande", "087852779418", "Servya, Renatih", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Overall good, tinggal touch up sedikit lagi. Mungkin tissue bisa taruh di bbrp titik, and tong sampah kecil di sekitar wastafel untuk tissue."],
        ["RUf", "-", "Munggu", "Enak", "Baik", "Nyaman", "Bersih", "Secara umum sudah baik, lebih hati-hati dalam \"repeat order\" agar pesanan tidak tertukar. Terima kasih."],
        ["CINTA", "081330490017", "Dam Indah no. 17", "Enak", "Baik", "Nyaman", "Bersih", "Perlu disediakan tempat sampah di samping wastafel untuk membuang bekas tissue. Kalau bisa tissue di setiap meja makan. TKS."],
        ["Gung Bagus", "085829707802", "Dalung", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih Sekali", "Piringnya suka jalan sendiri (kertas minyak) saat makan, kertas minyak di piring licin. Tidak ada tong sampah dekat wastafel, bingung buang tisu kemana ???"],
        ["Anton", "-", "Buduk", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Belum ada karena masih baru"],
        ["AMBA", "082166691937", "Dalung", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih Sekali", "Mantap"],
        ["ASTRI", "-", "Kebo Iwa", "Enak", "Baik", "Nyaman", "Bersih", "Sambal panggangnya dibanyakin"],
        ["(tidak diisi)", "0--", "Asli Dalung", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Mantap"],
        ["Amba", "-", "Dalung", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "TERBAIK !"],
        ["Sulastri", "081917108772", "Darmasaba", "Enak", "Baik", "Nyaman", "Bersih", "Sudah cukup baik"],
        ["Aulia & Eva", "089660158411", "Jl. Kroya", "Enak", "Baik", "Biasa", "Bersih", "Untuk Mejanya terlalu tinggi, agak susah untuk makan buat orang yang pendek :)"],
        ["Dina Aprilia", "085857730077", "Buduk", "Enak", "Baik", "Nyaman", "Bersih", "Seharusnya di dekat wastafel disediakan tempat sampah untuk bekas tisu cuci tangan."],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "NULL", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Hari Kesuma", "085857840305", "Lingk. Cica, Abianbase", "Enak", "Baik", "Nyaman", "Bersih", "Kursi kurang tinggi sehingga makan agak sulit untuk orang yang kurang tinggi."],
        ["Yopi", "-", "Sading, Mengwi", "Enak", "Baik", "Nyaman", "Bersih", "Makanannya enak, tempatnya nyaman dan juga pelayanannya ramah dan cepat. Suasananya ok, musiknya tidak terlalu berisik, pertahankan terus kualitasnya."],
        ["Echa", "-", "Dalung", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Kia", "081805955223", "Kapal", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Sudah baik... ramah sekali."],
        ["Irma", "083166273610", "MGW", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih Sekali", "Pelayanannya bagus sekali, disambut sama kakak ganteng dan maniez ❤️"],
        ["Ayu", "085738144981", "AbS", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "Sudah perfect senyum kakaknya manis eh :)"],
        ["Echa", "08560294984", "Buduk", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Anie", "08561443100", "Dalung", "Enak", "Baik", "Nyaman", "Bersih Sekali", "Staff saat hari raya lebih di banyakin lagi kak :) Supaya waktu penyajian gak kelamaan karena kehabisan."],
        ["Diah", "-", "-", "Enak", "Baik", "Biasa", "Biasa", "(tidak diisi)"],
        ["Cindana", "087754171", "Jl Raya Benasi", "NULL", "Baik Sekali", "Nyaman", "Bersih", "Sediakan tisu disetiap meja"],
        ["Dewi Utari", "-", "Badung", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Kurang adanya tisu disetiap meja. Nasi kurang soft. Hangat pagi yg tak bisa nasi dingin."],
        ["Amel", "-", "(tidak diisi)", "Enak", "Biasa", "Nyaman", "Biasa", "(tidak diisi)"],
        ["RADITYA", "082144837309", "Jl Gn Cennik V/16", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["ARNO", "-", "JL KEBO IWA", "Enak", "Biasa", "Nyaman", "Biasa", "Sesuai untuk harga segitu."],
        ["Sintya", "08174796611", "Padang Sambian", "Enak", "Baik", "Nyaman", "Bersih", "Semangat bekerja memberi pelayanan terbaik !!"],
        ["Amara", "088232289092", "Dalung", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Pertahankan keramahan dan pelayanannya ya, kak! Semangat kerjanya :)"],
        ["Saula", "-", "(tidak diisi)", "Enak", "Biasa", "Nyaman", "Biasa", "(tidak diisi)"],
        ["Bu Vivie", "081916666708", "JL. Pidada XI/23 Dps - Bali", "Biasa", "Biasa", "Tidak Nyaman", "Biasa", "Tidak Nyaman, karena masih ada aja lalat yg beterbangan."],
        ["Yuli", "087730429223", "Padangsambian", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Pelayanan sudah baik"],
        ["Salmon", "081237658979", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Yudi", "085738219693", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "Tidak ada karena sudah memuaskan."],
        ["BINTAR", "085334515925", "TABANAN", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "Porsinya lebih banyak lagi."],
        ["TEJO", "081916226900", "Denpasar", "Enak", "Baik", "Nyaman", "Bersih", "Kalau bisa porsi nasinya di perbanyak."],
        ["Nawa", "089518938916", "--", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Karina", "081970219817", "Dalung", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Makasih ya kak."],
        ["Mei", "-", "Canggu", "Enak Sekali", "Baik Sekali", "Biasa", "Bersih Sekali", "Sebaiknya ada hand dryer atau tissue di washtafel."],
        ["MIRANDA", "08960481604", "Br gegadon kapal", "Enak", "Baik", "Nyaman", "Bersih", "Mejanya sedikit lengket, mungkin bisa dibersihkan maksimal."],
        ["Gracelly", "082199088593", "Jln tegal sari", "Enak Sekali", "Baik", "Biasa", "Biasa", "Tingkatkan kenyamanan tempat."],
        ["APIK", "081899561333", "Perumahan SSM Munggu", "Enak", "Baik", "Nyaman", "Bersih", "Kebersihannya lebih ditingkatkan lagi. Ruangan agak panas mohon rasa ditambah kipas angin."],
        ["Degus", "-", "(tidak diisi)", "Enak", "Baik", "Tidak Nyaman", "Bersih", "Banyak asap di dalam buat sesak nafas. Makanan enak."],
        ["Vita", "08578317205", "jl muding Pertiwi no9", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Oke! makanan enak, best banget. Kak :D"],
        ["Yoni Tomohon", "0817569933", "Abianbase", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Dipertahankan dan tingkatkan lagi"],
        ["Dana", "083119856878", "Dalung", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Santi", "085930412114", "Abianbase", "Enak Sekali", "NULL", "Nyaman", "Bersih", "Semoga ada menu baru lainnya :)"],
        ["Sutri Jayanti", "087861846861", "Canggu", "Enak", "Baik", "Nyaman", "Bersih", "Di siang hari jarang ada parkir"],
        ["ARSYIFA", "0822-3414-3545", "Perum Gunung Sari", "Enak", "Baik", "Tidak Nyaman", "Biasa", "Untuk tempat diusahakan pake AC, untuk per-mejaan & tempat duduk lebih nyaman. Kipas angin terlalu kencang + suaranya begitu mengganggu. Lebih diperhatikan :)"],
        ["alex", "-", "JL surya bhuana", "Enak", "Baik", "Biasa", "Bersih", "(tidak diisi)"],
        ["Amel", "085792130663", "Dalung", "Enak", "Baik", "Biasa", "Bersih", "Tempatnya bising tapi ayamnya enak. Sambalnya kurang banyak."],
        ["I Gede Dimas Pradipo", "081237242779", "Pupuan", "Enak", "Baik", "Biasa", "Bersih", "(tidak diisi)"],
        ["Putu Surya Adinata", "085958092966", "Br. Batan", "Enak", "Baik", "Nyaman", "Bersih", "Banyakin promo"],
        ["Ni Putu Beatrice Shinta Wardani", "081558170608", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Biasa", "Sebelumnya terima kasih atas pelayanan yang baik dan ramah. Namun, sedikit kritik dari saya mungkin untuk kebersihan lantainya bisa ditingkatkan lagi agar pengunjung lebih nyaman."],
        ["CHRISTIAN", "085897952013", "jl. koeng sari I blok b no S.", "Enak", "Baik", "Nyaman", "Bersih", "Lantainya agak dibersihin kak"],
        ["Made Wiranda Adnyana", "085857329924", "Jl Tukad PANCORAN no. 8S.", "Enak", "Baik", "Biasa", "Biasa", "Terimakasih atas servicenya. Sebelumnya, saran saya suara kipasnya bisa dikondisikan lagi?"],
        ["Alex", "089661820020", "Dalung Blok HH", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Ade", "085739200865", "Dalung Permai", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Semoga bisa jadi lebih baik lagi. Semangat ya kakak-kakak, semoga selalu sehat dan bahagia!! :)"],
        ["PEGGY", "081331603999", "DALUNG", "Enak Sekali", "Baik", "Nyaman", "Biasa", "(tidak diisi)"],
        ["Putu Gunarta", "087756531771", "Nusa Dua", "Enak", "Baik", "Biasa", "Bersih", "Kipas perlu ditambah. Panas"],
        ["Nyoman", "081558700064", "Dalung", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Windu", "-", "Tabanan", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["OKTA", "-", "Tabanan", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Adi", "085602219766", "Dalung Permai", "Enak", "Baik", "Nyaman", "Biasa", "Lantai kurang bersih."],
        ["Pak Candon", "085238157807", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "Tidak ada wastafel untuk cuci tangan. (Makan di tempat)."],
    ],
    "Mengwi": [
        ["Nama", "No HP/WA", "Alamat", "Rate Makanan", "Rate Pelayanan", "Rate Kenyamanan", "Rate Kebersihan", "Kritik dan Saran"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Biasa", "Bersih", "Air wastafel mati."],
        ["Farel", "085792534", "Jl Ubung Mengwi", "Enak", "NULL", "Nyaman", "Bersih", "Kebersihan kurang, persediaan makanan kurang lengkap. Terimakasih."],
        ["Slesa", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "Sambel kurang bawang, bisa tambahin variasi mungkin sambel mentah."],
        ["Kristina", "083174900029", "Sobangan", "Enak", "Baik", "Nyaman", "Biasa", "Mungkin perlu di cek tissu di tempat cuci berkala dan kebersihannya jangan lupa wewangian ditutup jika tak ada orang."],
        ["Rakih", "-", "Pasek", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Septi", "-", "Tangeb", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Putu", "-", "Pasekan", "Enak", "Baik", "Nyaman", "Bersih", "Pertahankan kualitasnya."],
        ["Gung Oca", "-", "Tangeb", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Dwiki Pranata", "081237528025", "Banyar Tunggal Sari", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Tidak ada yang harus saya kritik, tentang ruangan nya semuanya ENAK. Cuman 25 menit menunggu pesanan. No Problem..."],
        ["NATRA/ERNI", "-", "BATURITI", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["John Strong", "0817340899", "Br. Wana Hijau, Jl. Batukaru Tabanan", "Enak", "Baik", "Nyaman", "Bersih", "Pertahankan & tingkatkan!"],
        ["NABILA", "087865190539", "WRDE", "Enak", "Baik", "Nyaman", "Biasa", "MOHON DITAMBAH PEMBAYARAN QRIS / CASHLESS LAINNYA"],
        ["Abdullah", "08777272098", "Jl. Pulau galang", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Ayamnya enak tapi tolong diletakkan di penghangat jadi customer dpt yg tidak dingin. Sayuran pelengkap sudah sangat banyak macamnya."],
        ["Ayu", "085864554858", "Tabanan", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Semuanya enak dari rasa ayam dan sambalnya mungkin kedepannya klo mau dikasih inovasi dibagian sambal dibagi level :) Thanks."],
        ["Iman", "085869189089", "Mengwi Jl bukit tinggi", "Enak", "Baik", "Nyaman", "Bersih", "Semoga Makin Laris Manis"],
        ["Nanda Alit", "-", "Mengwi", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Baik Dalam Penyajian"],
        ["APRI", "-", "BR. DUKUH", "Enak Sekali", "Baik", "Nyaman", "Bersih Sekali", "mantap"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Bu Topan", "087769712612", "Lingk. Muncans.", "Biasa", "Baik", "Nyaman", "Bersih", "Sopnya tambahin garnish (Timun, Selada). Kurangi pedasnya lagi sedikit :). NB: Siapkan tusuk gigi & tisu di atas meja !!!"],
        ["Robert wayan Ali", "082266686416", "Singsing", "Enak", "Baik", "Nyaman", "Bersih", "Di tingkatkan lagi"],
        ["Ni Made Klianti", "085792220820", "Punggul, Abiansemal", "Enak", "Baik", "Nyaman", "Bersih", "Tempat parkir kurang luas."],
    ],
    "Panjer": [
        ["Nama", "No HP/WA", "Alamat", "Rate Makanan", "Rate Pelayanan", "Rate Kenyamanan", "Rate Kebersihan", "Kritik dan Saran"],
        ["ayu", "081936601771", "Br. Bona, Blahbatuh, Gianyar", "Enak", "Baik", "Nyaman", "Bersih", "Nasi kurang banyak"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Biasa", "Biasa", "Kalo boleh, sambalnya pakai ulih. Terimakasih."],
        ["Risky Ferdiansyah", "08970841653", "Jl. Tukad Badung", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(coretan)"],
        ["Ayu", "089688011109", "Jl. Akasia XIII. B no. 9", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["Feby", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["nakha pradnya", "087861650065", "Sanur", "Enak", "Baik", "Biasa", "Biasa", "Kasih exhaust biar asapnya ke depan baik itu 1 & 2,Sambal banyak merica? ayamnya dingin"],
        ["Ketut", "082340913838", "(tidak diisi)", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["Vani", "087747921307", "Tukad Batanghari", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Banyakin dikit sambalnya ya kak.. hehe.. Makasih..."],
        ["Made", "085739380778", "Peguyangan Kangin", "Enak", "Baik", "Nyaman", "Bersih", "Membuat promo-promo menarik dan diskon <3 <3 <3"],
        ["Jakson wam", "082111399873", "Uluwatu", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Overall okay banget sih kak... udah bagus banget"],
        ["INDRA ADI WIJAYA", "08164735983", "Jl. GN. RINJANI no 7 Denpasar", "Enak", "Baik", "Biasa", "Biasa", "Fokus & utamakan urutan pemesanan ya.. - Untuk Cab. Dalung: Kebersihan yg utama, tambah kipas / penyejuk udara. - Untuk Cab. Panjer: Semangat Selalu, jaga kebersihan. - Untuk Cab. Patung: Semangat Selalu walau pos di daerah macet, sambal perlu diperhatikan sekat plastik anti debu jalan. OVERALL, ayam panggang paling enak, tinggal menjaga konsistensi rasa bumbu, kematangan ayam, porsi serta rasa sambal yang sudah cocok dengan ayamnya. Salam kompak :)"],
        ["Kadek Ani", "081238143203", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Semoga Selalu jaya."],
        ["Tami", "-", "(tidak diisi)", "Enak", "Baik Sekali", "Biasa", "Bersih", "Tempat makannya nyaman (di lt. 2) cuman mungkin karena gak ada jendela jadi agak pengap & lantainya agak lengket"],
        ["I Made Reynald Aldy", "0838-1967-2356", "Darmasaba, Abiansemal", "Enak", "Baik", "Tidak Nyaman", "Biasa", "Ayam terasa bumbunya dan lembut tapi tidak juicy. Lantai 2 terasa pengap dan sedikit panas. Tidak ada ventilasi udara."],
        ["Asti", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "Sudah Bagus.-"],
        ["Evani", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Kalau bisa di setiap meja di sediakan tissue"],
        ["AGUS", "085997271717", "Renon", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Nico", "085857311375", "(tidak diisi)", "Enak Sekali", "Baik", "Biasa", "Biasa", "Buat Free Refil nasi putihnya saja"],
        ["Cok", "081380371685", "Gatsu, Sobak dalem", "Enak Sekali", "Baik", "Biasa", "Biasa", "Buatkan free nambah nasi kebuli."],
        ["CAHYA", "082131227227", "jl. Yeh Aya", "Enak", "Baik", "Biasa", "Bersih Sekali", "(tidak diisi)"],
        ["Devi", "089675774161", "-", "Enak Sekali", "Baik", "Biasa", "Biasa", "(tidak diisi)"],
        ["Nanda / nanamiku", "081236536735", "Jl. Tukad Yeh aya", "Enak", "Baik", "NULL", "NULL", "(tidak diisi)"],
        ["Yosep Heri", "087810415397", "JLN. Kresna 66. Ikan Tongkol 1", "Enak Sekali", "Baik", "Biasa", "Bersih", "Kipas yang gede berisik banget bos!! Ha.. Ha.."],
        ["AYU", "-", "Jl. Y. Tukad yeh aya", "Enak", "Baik", "Biasa", "Bersih", "(tidak diisi)"],
        ["RINO", "08986573077", "(tidak diisi)", "Enak", "Baik", "NULL", "Biasa", "BUNYI PIPA SANGAT MENGGANGGU. RUANGAN PANAS"],
        ["TYO", "082215231710", "TUKAD YEH AYE IX, RENON", "Enak Sekali", "Baik Sekali", "Biasa", "Bersih", "Mikalau memungkinkan ruangan bisa diperbesar/diperluas untuk menambah kelapangan bagi pembeli/pelanggan yang ingin makan di gerai."],
        ["Netrarya", "081857127390", "-", "Enak", "Baik", "Nyaman", "Biasa", "Tadi ada serpihan kawat cuci piring di nasi saya"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Biasa", "Bersih Sekali", "Sediakan smoking room (kalau bisa). Dangke :)"],
        ["Alif", "085935357575", "SIDAKARYA", "Enak", "Baik", "NULL", "Biasa", "(coretan)"],
        ["Eri", "088271262776", "jl Pulau Nias, Denpasar", "Enak Sekali", "Baik Sekali", "Biasa", "Bersih Sekali", "Jangan ganti resep ya!"],
        ["WIRA", "081999974449", "KESIMAN", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["MADE", "087802426454", "RENON", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["DEVONI", "085229002900", "PANJER", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Kebersihan alat makan bisa lebih ditingkatkan."],
        ["Citta lestari", "089524662524", "Jl. Tantri Gg. I No. 1", "Enak", "Baik", "Nyaman", "NULL", "Lebih banyak meja makan"],
        ["Wawan", "082152492897", "Jl. T. Yeh aya", "Enak", "Baik Sekali", "Biasa", "Bersih", "(tidak diisi)"],
    ],
    "Pemogan": [
        ["Nama", "No HP/WA", "Alamat", "Rate Makanan", "Rate Pelayanan", "Rate Kenyamanan", "Rate Kebersihan", "Kritik dan Saran"],
        ["YONO Oktave", "08361128956", "Jalan kesehatan", "Enak Sekali", "Baik Sekali", "Nyaman", "Biasa", "(tidak diisi)"],
        ["Sayang", "08123745080", "Badung / Bali", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Good job, dipertahankan lagi kebersihan nya."],
        ["(tidak diisi)", "-", "(tidak diisi)", "Biasa", "Biasa", "Biasa", "Biasa", "(tidak diisi)"],
        ["Rizki", "085829212707", "Benoa", "Enak", "Baik", "Nyaman", "Bersih", "(coretan)"],
        ["Mas Amba", "-", "Jl. Raya Mojo - Jomkerto", "Enak", "Baik", "Biasa", "Biasa", "Kasi diskon buat ayam utuhnya. Saosnya enak cukup untuk 1 porsi. Untuk harga saos mungkin bisa diturunkan lagi."],
        ["Gongwidi", "081803612041", "Jl. Imam bonjol gg. air mancur", "Enak", "Baik", "Nyaman Sekali", "Bersih", "Kalau bisa setiap waktu, untuk semua menu harus ready."],
        ["Resmaliana", "083143095352", "Pesanggaran", "Enak Sekali", "Baik", "Biasa", "Biasa", "Sebaiknya pilihan minuman lebih banyak lagi & kepedasan sambal dikurangi."],
        ["Danci Uxtin", "089676098371", "Yn. Gunung mas Tegal Buah", "Enak", "Baik", "Nyaman", "Bersih", "Nothing"],
        ["IDA AYU MARDANI", "081933101669", "MUTIARA INDAH - PEMOGAN", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Ada lagi di Seminyak lebih enak"],
        ["Tania", "082257093312", "Pemogan", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih", "Untuk cust yg take away agar tidak duduk di kursi dine in, karena saat ramai tempat duduknya terbatas. Semangat!!"],
        ["welly", "08179706527", "jalan palm III no 11", "Enak", "Baik", "Biasa", "Biasa", "Buka Cabang di jimbaran / Nusa Dua"],
        ["zahra", "085792157134", "pelanggaran", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["jasmine", "081359198987", "Taman Ayu, Pulau Galang", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Alex jabat", "081336289254", "Jl. Pulau Yoni", "Enak", "NULL", "Biasa", "Biasa", "Ruanganya tambahin AC"],
        ["Jokowi", "089666199127", "Jalan Pulau Yoni gang Rindani", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Diskon Pliss :)"],
        ["Ica", "082341074760", "Tohpati", "Enak Sekali", "Baik", "NULL", "Bersih", "Sambalnya kurang banget kak"],
        ["Haykal Barej", "081515582903", "Jalan Pulau Batang no. 3", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "NULL", "Kalo bisa nambah nasi sepuasnya GOGO pasti bangkrut"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik Sekali", "Biasa", "Bersih", "Makanannya enak. Karna namanya enakko mungkin kalau namanya enak sekaliko bisa jadi makanannya ENAK SEKALI"],
        ["PUTU", "082145229678", "Jl. Pemogan", "Enak", "Baik Sekali", "Biasa", "Bersih", "Tempatnya agak berisik... Kurang tertutup kalau untuk makan ditempat"],
        ["VALEN", "081288051987", "PEMOGAN", "Enak", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Elsi", "081230804372", "Pedungan", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Tolong sediakan asbak untuk perokok. T-tanks"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik Sekali", "Nyaman Sekali", "Bersih", "Nasi Merah Stock nya bisa diperbanyak supaya tidak kehabisan terus :)"],
        ["(tidak diisi)", "-", "Pemogan", "Enak", "Baik Sekali", "Nyaman", "Biasa", "Nasi Kering, Sedikit Dingin & Basah."],
        ["Ajik", "-", "Pemogan", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["GIA'ZA", "-", "Besakih 3 Pemogan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "Sudah nyaman, porsi pas. Ayam diperhatikan jangan sampai kulitnya gosong pahit. Good job team v"],
        ["Pitri", "087747928421", "Jl. Aprilaga no 6 Peguyangan", "Enak", "Baik", "Nyaman", "Biasa", "Tingkatkan lagi."],
        ["(tidak diisi)", "-", "(tidak diisi)", "NULL", "Baik Sekali", "Nyaman", "NULL", "(tidak diisi)"],
        ["Litta", "081239857972", "Jl Gn Saliran No. 39i", "Enak", "Baik", "Nyaman", "Bersih", "ENAK BINGIT! Kak"],
        ["tamira", "-", "(tidak diisi)", "Enak", "Biasa", "Nyaman", "Biasa", "Seharusnya saosnya bisa ditukar"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Ayamnya enak sesuai namanya enakko ^^!~"],
        ["Jessy", "08980391028", "Jl. Raya Pemogan Gg. Dewi Uma III No. 15", "Enak", "Baik", "Nyaman", "Bersih", "-"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Biasa", "Biasa", "Biasa", "Lantainya lebih bersih lagi agar lebih nyaman buat pengunjung dine in."],
        ["ABRAHAM", "081707007070", "Taman Bencing Barat, 72A", "Enak", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["ADam", "085791037104", "(tidak diisi)", "Biasa", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Hendra", "-", "Kesiman", "Enak", "Baik", "Nyaman", "Biasa", "Lebih dijaga cita rasa dan kebersihan."],
        ["ARIEL", "-", "(tidak diisi)", "Enak", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Siti", "089838175415", "Pulau lingga Pedungan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Makin semangat terus kak!! :) ❤️"],
        ["Maureen", "081290794998", "Jakarta", "Enak", "Baik", "Nyaman", "Tidak Bersih", "1. Sambal terlalu pedas, terbakar. 2. Tolong perhatikan kebersihan mencuci alat makan! (Sendok, garpu) 3. Tolong perhatikan kualitas es batu ada serbuk putih. Thank you :)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "NULL", "Baik Sekali", "Nyaman", "Bersih Sekali", "(tidak diisi)"],
        ["Revlin", "081237000770", "Pemogan", "Enak Sekali", "Baik", "Biasa", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "Enak dan gurih, saos nya enak."],
        ["Fitri", "0895385485344", "Jl. Pemogan", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih Sekali", "Over all bagus, tetap semangat sukses selalu"],
        ["TRI", "082328195213", "Pulau moyo", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Buka banyak cabang :)"],
        ["Ayu", "087814758993", "Gg. Dewi Uma Pemogan", "Enak", "Baik", "Nyaman", "Biasa", "Ayamnya enak cuma bumbunya kurang meresap ke daging bagian dalamnya. semangat! ^^"],
        ["I Putu Arie Argantha", "-", "-", "Enak", "Baik", "Biasa", "Biasa", "jaga kebersihan + pantau refill lalapan."],
        ["DIO", "-", "JLN TUKAD BADUNG", "Enak", "Biasa", "Biasa", "Biasa", "Tempat sambal lebih bagus menggunakan cawan"],
        ["Dessy", "085852712309", "Jl. raya pemogan gg. Anggrek 9D", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih Sekali", "(tidak diisi)"],
        ["Jokowi", "-", "(tidak diisi)", "Enak", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["EDwin.", "081904462133", "Pulau moyo", "Enak", "NULL", "Nyaman", "Bersih", "(tidak diisi)"],
        ["ADELIA", "-", "DENPASAR PEMOGAN KOMPLEK VILLA TAMAN AYU", "Enak", "Baik", "Nyaman", "Bersih Sekali", "OKE. MOHON MAAF SEKALI LAGI BUKAN SAMA KARYAWAN PEREMPUAN KEMARIN SAYA MERASA KURANG RAMAH KARENA MUKA KETAWA SAMPAI MELULU. OK THANK YOU :)"],
        ["Alin", "082-144-093-044", "Jln Imam Bonjol", "Enak", "Baik", "Biasa", "Biasa", "(tidak diisi)"],
        ["ARI", "081330988328", "Pemogan", "Enak", "Baik", "Nyaman", "Bersih", "Lebih baik ruangan tertutup dan diberi AC karena ada lalat saat makan, jadi kurang nyaman saat makan."],
        ["ivana", "081999092377", "jl. Pantai Kuta no 39A", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Budi", "-", "Bali", "Enak", "Baik", "Nyaman", "Biasa", "(tidak diisi)"],
        ["Yuli", "081916918332", "Jl. Uluwatu", "Enak", "Baik", "Nyaman", "Biasa", "Mungkin lantai aja"],
        ["Pipin", "-", "Jl Juwet sari gg lebak sari II", "Enak", "Baik", "Biasa", "Biasa", "Di perluas lagi tempat duduknya"],
        ["Stephan", "081352113045", "(tidak diisi)", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Gelasnya kurang gede"],
        ["RANDY", "085618770984", "Jln BKR an", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Haykal Bajrey", "081515582903", "Jalan Rukan Galang No. 3", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "NULL", "Baik Sekali", "Nyaman", "Bersih Sekali", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "NULL", "NULL", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "NULL", "(tidak diisi)"],
        ["Ayu sekar", "085737617285", "Mekar Blok A8 No 39", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["NKN", "082144136762", "pulau Bungin xx", "Biasa", "Biasa", "Biasa", "Bersih", "1. Pintu toilet di bagian dalam spy diberi tarikan - susah tarik pintu dari dalam. 2. Lalapan gratis nya sering kosong wkwkwk - hahaha"],
        ["Haykal Bajrey", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Kadek Pradita", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["ASRORI", "081999073049", "P. bungu gg Damar III A1", "Enak", "Baik", "Nyaman", "Bersih", "Nasinya terlalu asin. Ayamnya uda mantap gurih lembut."],
        ["Ayu", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["VIVI", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Rassri", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Husna", "087860784196", "P-Bungu gg Damar III no 1", "Enak", "Baik", "Nyaman", "Biasa", "Nasinya kebuli ASIN"],
        ["Frans", "-", "(tidak diisi)", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Hanya cabe terlalu dikit, selain itu ok."],
        ["William", "085339838888", "Jln. Mekar block D, no 5", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Dewi Kumara", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Keiko", "085161276600", "Sesetan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "NULL", "Bagus sekali, kalo bisa porsi nasinya dilebihin kak :)"],
        ["Tegar", "085820176356", "P. Bungin gg Damar A no 1", "Enak", "Baik", "Nyaman", "Biasa", "Nasi kebulinya Asin. Soalnya ga suka asin"],
        ["Elva", "0856470218338", "(tidak diisi)", "Enak Sekali", "Baik", "Biasa", "Bersih", "Pilihan nasinya tolong dibuat agar available semua"],
        ["ERO", "-", "UBud", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["REZA", "-", "Pemogan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Eka Malini Cahyani", "-", "Jln Ponda Saselan Pondok Gadoeh", "Enak", "Baik", "Nyaman", "Bersih", "Tempatnya lumayan panas, tapi gak panas banget"],
        ["Ragardana", "081547581929", "jl.sesetan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Sudah baik"],
        ["Aryawangsa", "-", "Jembrana", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Tidak ada :)"],
        ["Ivan", "082127729810", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Refill es teh"],
        ["Linus manur", "087753184489", "Kesiman Petilan", "Enak", "Biasa", "Biasa", "Tidak Bersih", "Kurang bersih ya kak."],
        ["Sari", "089644669486", "Jln. Gatot Subroto", "Enak", "Biasa", "NULL", "Biasa", "Mantab Anjay Mantab !"],
        ["Arya", "081370866821", "Jl. Guntu No 18", "Enak", "Biasa", "Biasa", "Biasa", "(tidak diisi)"],
        ["Vivi", "-", "Pemogan", "Enak Sekali", "Baik", "Biasa", "Bersih", "Sambelnya kurang banyak, pedasnya pass dan nampol. Ayamnya rasanya enak dan lembut :)"],
        ["Mohamed Nizar", "-", "Pedungan", "Enak", "Biasa", "Biasa", "Biasa", "tidak ada"],
        ["Wahyu", "085-1711-41519", "Selawati, Gianyar Bali", "Enak", "Baik", "Nyaman", "Bersih", "Sudah sangat baik, terima kasih Paklik"],
        ["IKON", "087828586131", "Besetan", "Enak Sekali", "Baik", "NULL", "Bersih", "Overall Okay. Cuman wewangiannya agak wadidaw aja."],
        ["Sarinah", "-", "Pemogan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Juminten", "-", "Pemogan", "Enak Sekali", "Baik Sekali", "Tidak Nyaman", "Bersih Sekali", "(tidak diisi)"],
        ["Rita", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Sutra", "-", "(tidak diisi)", "Enak", "Baik", "Biasa", "Bersih", "Setiap meja isikan tisu untuk lap sesudah makan."],
        ["wita", "-", "DPS", "Enak", "Baik", "Nyaman", "Bersih", "Ok"],
        ["Dwi", "087860281760", "Pemogan", "NULL", "Baik Sekali", "Nyaman", "NULL", "Mantap"],
        ["Dewi", "081239106189", "Jl. P. Adi dalam no 7", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Indah", "081846633068", "Antasura", "Enak", "Baik", "Biasa", "Biasa", "Mantap..."],
        ["Sari", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["ISNA", "085879923202", "Tukad Batanghari, Panjer", "Enak Sekali", "Baik", "Nyaman", "Biasa", "Sambalnya banyakin ya, gelas es teh digedein kak."],
        ["Nursyam Musfirah. R", "0852-4270-8778", "Akasia 6 - Hayam Wuruk", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Sambelnya ditambah sizenya :) Upgrade size es teh juga kak."],
        ["Armita", "089669834428", "Teuku Umar", "Enak Sekali", "Baik", "Nyaman", "Bersih", "es teh mau nambah banyak."],
        ["Sofia", "082174754905", "Tukad Batanghari, Panjer", "Enak Sekali", "Baik", "Nyaman", "NULL", "es teh kurang banyak, samel juga kurang banyak. makan pak."],
        ["DILA", "0821461289", "VI NOJA PENINSAR", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Siluman Tamimi", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Biasa", "(tidak diisi)"],
        ["Yasmin", "-", "Pemogan", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Biasa", "Biasa", "(tidak diisi)"],
        ["Rian", "081529817174", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Bagus", "-", "Gianyar", "Enak", "Baik", "Nyaman", "Bersih", "Sambal dan Es Teh kurang banyak untuk 1 Porsi"],
        ["RAS", "0895800056106", "(tidak diisi)", "Enak", "Baik", "Biasa", "Biasa", "(tidak diisi)"],
        ["Fajar Patori", "-", "Ubung Kaja", "Enak Sekali", "NULL", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Julian", "0878939983", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "Nasi kebuli nya kurang kaku"],
        ["IZZU", "089652113069", "Jl. Nakula", "Enak", "Baik Sekali", "Nyaman", "Bersih", "Tidak ada, all good, terima kasih"],
        ["(tidak diisi)", "-", "(tidak diisi)", "NULL", "NULL", "Nyaman Sekali", "Bersih", "Pintu gudang WC telah harus tertutup / Dibuat penyekat / penghalang agar tak terlihat"],
        ["Melly", "-", "Serang Banten", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["EDI", "089777399999", "Pontianak", "NULL", "Biasa", "Biasa", "Biasa", "(tidak diisi)"],
        ["Kukuh Khoirul Iman", "085338845125", "Jl. Juwet Sari", "Enak", "Baik", "Nyaman Sekali", "Bersih Sekali", "Saran saya untuk kedepannya untuk karyawan mungkin sapaan ke konsumen yang datang, biar konsumen makin banyak karena terkesan diperhatikan pegawai."],
        ["Ryan", "-", "Tabanan", "Enak", "Baik", "Nyaman", "Bersih", "Sambalnya ditambah."],
        ["Made", "-", "Tabanan", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["ACD", "087885812500", "Jl. P. Lingga no. 4", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Wayan", "081390779283", "Asrama Polsek Kuta", "Enak Sekali", "Baik", "Nyaman", "Bersih Sekali", "(tidak diisi)"],
        ["SAVI", "088987268112", "PEMOGAN", "NULL", "Baik Sekali", "Nyaman", "Bersih", "Gada kritik dan saran banyak, tapi beberapa kali makan disini, kadang ayamnya kurang hangat, tapi untuk rasa gada lawan!"],
        ["wira", "-", "Dps", "Enak", "Baik", "Nyaman", "Bersih", "Bisa ditambah timun atau salad agar ada serat dalam tiap paketnya."],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["YOGA", "-", "SIDAKARYA", "Enak", "Baik", "Biasa", "Biasa", "(tidak diisi)"],
        ["NN", "-", "(tidak diisi)", "Enak", "Baik", "Biasa", "Biasa", "(tidak diisi)"],
        ["NN", "-", "(tidak diisi)", "Enak", "Biasa", "Biasa", "Biasa", "(tidak diisi)"],
        ["HARIS", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "❤️"],
        ["Orvina", "089608096054", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Mantap."],
        ["Aurellia", "085142914700", "Jl. Mekar Jaya Blok B II A No. 47", "Enak Sekali", "Baik", "Biasa", "Biasa", "Ini kita udah beberapa x makan / bungkus yang hari ini nasi kebuli nya rasanya asin dan agak lembek."],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["Adum tegar (Pecinta Setia)", "081236547829", "pemogan", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih", "Jangan pernah tutup, jangan dinaikin harganya, semangat staffnya memuaskan. Bill numpuk"],
    ],
    "TP": [
        ["Nama", "No HP/WA", "Alamat", "Rate Makanan", "Rate Pelayanan", "Rate Kenyamanan", "Rate Kebersihan", "Kritik dan Saran"],
        ["Nglek", "0857....0009", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Ngurah", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "NULL", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Wayan", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Nyoman", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["GEDE", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["ani Pitaloka", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "NULL", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman", "NULL", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "NULL", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Ramah Banget"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "NULL", "Baik", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["AGUNGAN", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["ngurah", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "NULL", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Linda", "083117220640", "Gn Patas", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Teja", "085710295136", "Canggu", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["Mega", "087860297033", "Padang sambian", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Davina karamoy", "081321909777", "Jananin aja dulu", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Staff Ramah"],
        ["Hilmi", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Ayu", "08193660350", "Taman Sekar IA No 5", "Enak", "Baik", "Nyaman", "Biasa", "(tidak diisi)"],
        ["Agix", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["RD", "08181415675", "Jl Gn Mas X/11 A", "Enak", "Biasa", "Biasa", "Tidak Bersih", "Harus perhatian lebih kepada kebersihan alat makan (sendok) karena faktor yg sangat penting dlm.."],
        ["Devia", "08377300279", "Buana Raya, Gg. Buana Dwipa", "Enak Sekali", "Baik", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Jaya", "-", "(tidak diisi)", "Enak", "Baik", "Nyaman", "Bersih", "Semuanya sudah sangat baik."],
        ["Robby", "081539604933", "(tidak diisi)", "Enak", "Baik", "Biasa", "Bersih", "Tambah Sambal Gratis"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Biasa", "(tidak diisi)"],
        ["Danna", "-", "-", "Enak", "Baik", "Nyaman", "Biasa", "(tidak diisi)"],
        ["Killa Syahril", "08155732806", "Jln. Mahendradatta", "Enak", "Baik", "Nyaman", "Bersih", "Tempatnya kurang luas, ruangan ber AC, parkiran mobil."],
        ["Lily", "087-752371242", "Gn. Bromo", "Enak Sekali", "Baik Sekali", "Biasa", "Bersih Sekali", "Tempat dine in bisa di upgrade"],
        ["Irul", "085895985779", "Kerobokan", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Makanan enak sudah baik"],
        ["Diah", "087780597414", "Buana Raya", "Enak", "Baik Sekali", "Biasa", "Biasa", "Pertahankan pelayanan. Tingkatkan kebersihan."],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Biasa", "Biasa", "(tidak diisi)"],
        ["Rudi", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Khabib", "081364031013", "Gunung Agung Gg. Bumi Ayu", "Enak Sekali", "Baik Sekali", "Biasa", "Bersih Sekali", "Dibebarapa aspek rasa terkadang agak keasinan. Control cara mengolah nasi briyani agar tidak terlalu lembek. :) Terimakasih"],
        ["Esa.", "08133959096", "Tegal buah", "Enak", "Baik", "Biasa", "Biasa", "Sukses Selalu !!"],
        ["Pt Popo Gt.", "-", "jln. Buana raya", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Kalau bisa untuk sambelnya di kasi varian. Contoh sambal matah, geprek, dan bumbu dari ayam tersebut, makasi \"!!\""],
        ["Bagus", "-", "Padang Sambian", "Enak Sekali", "Baik", "Biasa", "Biasa", "(tidak diisi)"],
        ["Abi", "-", "Mudimg", "Enak", "Biasa", "Biasa", "Bersih", "\"3S\" Senyum, Salam, Sapa. Semangat :)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "(tidak diisi)"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Biasa", "Bersih", "(tidak diisi)"],
        ["Maya.", "089665992309", "Jl. Buana Raya gg. buana kartika.", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["Kezia", "082283891002", "Kerobokan", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Bersih Sekali", "Tolong sediain tissu dimeja makan. Mungkin untuk porsi nya lebih ditambah lagi ya untuk harga segitu, overall rasanya oke banget, bumbunya berasa dagingnya empuk. ❤️"],
        ["(tidak diisi)", "-", "(tidak diisi)", "Enak", "Baik", "Biasa", "Bersih", "(tidak diisi)"],
        ["Wulan", "-", "(tidak diisi)", "Enak Sekali", "Baik Sekali", "Nyaman Sekali", "Biasa", "Mungkin tempatnya agar ditata lebih rapi lagi."],
        ["Nicky", "081290792279", "Denpasar", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "(tidak diisi)"],
        ["De Anto", "081239022109", "Jl Gn Batukaru, Denpasar", "Enak Sekali", "Baik", "Nyaman", "Bersih", "Semoga makin sukses, sehingga bisa membuka di tempat yang lebih luas dan nyaman"],
        ["Angel", "085965772067", "Denpasar", "Enak", "Baik", "Nyaman Sekali", "Bersih", "Sediakan tisu di setiap meja"],
        ["Dika", "-", "Denpasar bali", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "Mantap. Es tehnya bisa dikurangi gulanya :)"],
        ["Chelssy", "-", "Denpasar", "Enak Sekali", "Baik Sekali", "Nyaman", "Bersih", "-"],
    ],
};
